function array = ReadSlice(filename)
% Read the bin image generated by Gergely when doing the customised cut of
% the reference template and atlas
% Input  : filename (absolute path) fo the bin image
% Output : matlab array
%
stream = java.io.ObjectInputStream(java.util.zip.InflaterInputStream(java.io.FileInputStream(filename)));
array  = stream.readObject;
stream.close;

return